# Generated by Django 3.0.4 on 2020-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('criado_por', models.IntegerField()),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
